<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Infrastructure.EventsManagement</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit.EntityFrameworkCore"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application.EventsManagement\Application.EventsManagement.csproj" />
        <ProjectReference Include="..\Domain.EventsManagement\Domain.EventsManagement.csproj" />
        <ProjectReference Include="..\..\..\CommonLibraries\Infrastructure\Infrastructure.csproj" />
        <ProjectReference Include="..\Messages.EventsManagement\Messages.EventsManagement.csproj" />
        <ProjectReference Include="..\Messaging.EventsManagement\Messaging.EventsManagement.csproj" />
    </ItemGroup>
    
</Project>
