<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\CommonLibraries\Application\Application.csproj" />
      <ProjectReference Include="..\..\Bookings\Messages.Bookings\Messages.Bookings.csproj" />
      <ProjectReference Include="..\Domain.EventsManagement\Domain.EventsManagement.csproj" />
      <ProjectReference Include="..\Messages.EventsManagement\Messages.EventsManagement.csproj" />
    </ItemGroup>

</Project>
